version: 0.2

env:
  secrets-manager:
    TOEKN: "myToken:tokenForSonar"

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - yum install -y jq
      - yum install -y wget

  build:
    commands:
      - mvn clean verify sonar:sonar -Dsonar.projectKey=cybersandyorg -Dsonar.organization=cybersandyorg -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=$TOEKN
      - sleep 5
      - |
        quality_status=$(curl -s -u $TOEKN: "https://sonarcloud.io/api/qualitygates/project_status?projectKey=cybersandyorg" | jq -r '.projectStatus.status')
        echo "SonarCloud analysis status is $quality_status"
        if [ "$quality_status" = "ERROR" ]; then
          exit 1
        fi

  post_build:
    commands:
      - echo "Installing OWASP ZAP"
      - wget https://github.com/zaproxy/zaproxy/releases/download/v2.16.0/ZAP_2.16.0_Linux.tar.gz
      - tar -xvf ZAP_2.16.0_Linux.tar.gz
      - cd ZAP_2.16.0
      - ./zap.sh -cmd -quickurl https://www.example.com -quickprogress -quickout ../zap_report.html

artifacts:
  files:
    - zap_report.html
