version: 0.2
env:
  secrets-manager:
    TOEKN: myToken:toeknForSonar
phases:
  install:
    runtime-versions:
      java: latest
  build:
    commands:
      - mvn clean verify sonar:sonar -Dsonar.projectKey=cybersandyorg -Dsonar.organization=cybersandyorg -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=$TOEKN
