version: 0.2
phases:
  install:
    runtime-versions:
      java: latest
  build:
    commands:
      - mvn verify sonar:sonar -Dsonar.projectKey=cybersandyorg -Dsonar.organization=cybersandyorg -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=2182f4883693b02b13434b934f507bbcaf674ef9
